[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.run]
script = '''
#!@duckscript

exec cargo build --target wasm32-unknown-unknown --release --package plugin
exec cargo run --package vm
'''

[tasks.run-native]
script = '''
#!@duckscript

exec cargo build --release --package lib_native
exec cargo run --package vm_native
'''
